version: '3.8'
services:
  playwright-python:
    image: prudnikov21/playwright_vnc:latest
    ports:
      - "13901:5900"
      - "9323:9323"
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    volumes:
      - ./test-results:/app/test-results
      - ./tests:/app/tests
    tty: true
    stdin_open: true
