name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_REPO: prudnikov21/playwright_vnc

jobs:

  test:
    name: Test Docker image functionality
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Start Docker container
        run: |
          docker-compose -f docker-compose.build.yml up -d
          sleep 10
     
      - name: Check container status and VNC port
        run: |
          echo "Checking container status..."
          docker-compose -f docker-compose.build.yml ps
          
          echo "Checking if VNC port is accessible..."
          for i in {1..5}; do
            if nc -z localhost 13901; then
              echo "VNC port is accessible!"
              exit 0
            fi
            echo "Attempt $i: VNC port not accessible yet, waiting..."
            sleep 5
          done
          echo "Failed to connect to VNC port after 5 attempts"
          docker-compose -f docker-compose.build.yml logs
          exit 1
      
      - name: Run Playwright tests
        run: |
          docker-compose exec -T playwright-python pytest tests/test_example.py -v
      
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    # Only run this job for pushes to main and tags, not for PRs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: prudnikov21
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.DOCKER_HUB_REPO }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=ref,event=tag

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
